import pymongo
from dotenv import load_dotenv
import os
import certifi


"""
HackDavis Project - Table Schemas
(comment generated by Claude Code)

## sensor_readings

Stores raw time-series readings ingested from physical sensors. Each document
captures a single polling snapshot of a sensor's environmental and mechanical
metrics. The `text_repr` and `embedding` fields support LangChain RAG retrieval
by making each reading semantically searchable.

{
  "sensor_id": "sensor-004",
  "timestamp": 1746643200,
  "temperature": 82.4,
  "pressure": 14.7,
  "vibration": 0.38,
  "text_repr": "Sensor sensor-004 at 1746643200: temperature=82.4, pressure=14.7, vibration=0.38",
  "embedding": [0.0412, -0.1183, 0.2754, 0.0891, -0.0567, 0.3102]
  // ... 384 floats total, generated by all-MiniLM-L6-v2
}
```

---

## predictions

Stores structured LLM outputs generated after each sensor reading cycle. Each
document represents the model's risk assessment, anomaly classification, and
recommended actions for a given sensor at a point in time. Alert delivery
metadata (`alert_sent`, `alert_type`) is co-located here so the alert pipeline
can avoid duplicate notifications.

{
  "sensor_id": "sensor-004",
  "timestamp": 1746643200,
  "risk_pct": 67.5,
  "trend_direction": "rising",
  "notices": [
    "Temperature has increased 12% over the last 10 readings.",
    "Vibration approaching warn threshold."
  ],
  "recommended_next_steps": [
    "Schedule preventive inspection within 24 hours.",
    "Reduce operational load on affected unit."
  ],
  "confidence": 0.84,
  "predicted_values": {
    "temperature": 86.1,
    "pressure": 15.2,
    "vibration": 0.45
  },
  "anomaly_detected": true,
  "anomaly_type": "drift",
  "severity": "medium",
  "anomaly_description": "Gradual upward drift in temperature and vibration over the past 30 minutes.",
  "affected_metrics": ["temperature", "vibration"],
  "threshold_breached": false,
  "alert_sent": true,
  "alert_type": "sms"
}
```

---

## llm_logs

Captures every raw interaction with the Llama LLM for debugging, auditing, and
fine-tune feedback collection. Logs cover all three invocation modes: scheduled
prediction, anomaly classification, and interactive chat. `fallback_used` flags
responses where parse failure caused the system to reuse the last valid
prediction rather than the current output. Prompt will stay the same across 
each LLM call cycle, but `prompt_summary` distills the key context for easier analysis. 

```json
{
  "timestamp": 1746643205,
  "mode": "prediction",
  "sensor_id": "sensor-004",
  "prompt_summary": "You are a sensor analysis assistant. Given the following recent readings for sensor-004, assess risk and detect anomalies. Readings: [{temp: 82.4",
  "raw_output": "{\"risk_pct\": 67.5, \"trend_direction\": \"rising\", \"notices\": [\"Temperature has increased 12%\"], \"confidence\": 0.84, \"anomaly_detected\": true}",
  "parse_success": true,
  "confidence": 0.84,
  "fallback_used": false,
  "latency_ms": 1342
}
```

---

## users

Stores registered user accounts and their sensor subscriptions and alerting
preferences. The `thresholds` object drives the SMS (TextBee) and voice call
(ElevenLabs) alert routing logic: `warn_risk_pct` triggers an SMS and
`critical_risk_pct` triggers a voice call. `pending_dynamic_thresholds`
accumulates LLM-suggested threshold adjustments awaiting user approval.

```json
{
  "user_id": "a3f1c2d4-8b7e-4e2a-9c0f-1d6b5e3a2f87" (primary key)
  "phone": "+15105550192",
  "registered_sensors": ["sensor-004", "sensor-011", "sensor-023"],
  "thresholds": {
    "warn_risk_pct": 55.0,
    "critical_risk_pct": 80.0,
    "raw_thresholds": {
      "temperature": { "warn": 85.0, "critical": 100.0 },
      "pressure": { "warn": 16.0, "critical": 20.0 },
      "vibration": { "warn": 0.50, "critical": 0.75 }
    }
  },
  "pending_dynamic_thresholds": [
    {
      "suggested_by": "llm",
      "metric": "vibration",
      "suggested_value": 0.42,
      "suggested_at": 1746556800,
      "status": "pending"
    }
  ]
}
```

---

## snapshots

Tracks exports of historical sensor readings compiled for LLM fine-tuning jobs.
Each snapshot covers a contiguous time window for a single sensor and points to
a compressed CSV on disk or object storage. `fine_tune_job_id` is populated once
the snapshot is submitted to the fine-tuning pipeline, enabling status tracking
across both systems.

```json
{
  "snapshot_id": "d7e2b1a9-3f4c-4d8e-bc21-9a0f6e5c7d43",
  "sensor_id": "sensor-004",
  "created_at": 1746643200,
  "row_count": 8640,
  "file_path": "snapshots/sensor-004/1746643200.csv.gz",
  "status": "complete",
  "fine_tune_job_id": "ftjob-20260508-004",
  "rows_from": 1745433600,
  "rows_to": 1746643200
}
```

"""

class MongoDBConnector:
    default_db_name = ""
    def __init__(self, project_env=".env"):
        load_dotenv(dotenv_path=project_env, override=True)
        try:
            self.url = os.getenv("MONGODB_URL")
            self.client = pymongo.MongoClient(self.url, tlsCAFile=certifi.where())
            print("MongoDB client initialized successfully.")
        except Exception as e:
            print(f"Error initializing MongoDB client: {e}")
            self.client = None

    def set_default_db(self, db_name):
        self.default_db_name = db_name

    def insert_data(self, collection_name, db_name=None, data=None):
        if not self.client:
            print("MongoDB client not initialized.")
            return {"status": "error", "message": "MongoDB client not initialized."}
        try:
            db = self.client[db_name] if db_name else self.client[self.default_db_name]
            collection = db[collection_name]
            result = collection.insert_one(data)
            print("Success")
            return {"status": "success", "inserted_id": str(result.inserted_id)}
        except Exception as e:
            print(f"Error inserting data into MongoDB: {e}")
            return {"status": "error", "message": str(e)}
    
    def pull_data(self,  collection_name,db_name=None, query=None):
        if not self.client:
            print("MongoDB client not initialized.")
            return {"status": "error", "message": "MongoDB client not initialized."}
        try:
            db = self.client[db_name] if db_name else self.client[self.default_db_name]
            collection = db[collection_name]
            if query:
                results = collection.find(query)
            else:
                results = collection.find()
            return {"status": "success", "data": [result for result in results]}
        except Exception as e:
            print(f"Error pulling data from MongoDB: {e}")
            return {"status": "error", "message": str(e)}
    
    def pull_by_timerange(self, collection_name, db_name=None, start_time=None, end_time=None):
        if not self.client:
            print("MongoDB client not initialized.")
            return {"status": "error", "message": "MongoDB client not initialized."}
        try:
            db = self.client[db_name] if db_name else self.client[self.default_db_name]
            collection = db[collection_name]
            query = {}
            if start_time and end_time:
                query["timestamp"] = {"$gte": start_time, "$lte": end_time}
            elif start_time:
                query["timestamp"] = {"$gte": start_time}
            elif end_time:
                query["timestamp"] = {"$lte": end_time}
            results = collection.find(query)
            return {"status": "success", "data": [result for result in results]}
        except Exception as e:
            print(f"Error pulling data from MongoDB: {e}")
            return {"status": "error", "message": str(e)}